# Generated by Django 5.1.2 on 2024-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
