# Generated by Django 5.1.2 on 2024-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
