# Generated by Django 5.1.2 on 2024-12-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_submission_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the marking scheme', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_scheme', to='api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='The text of the answer')),
                ('marks', models.PositiveIntegerField(help_text='Marks allocated for this answer')),
                ('marking_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.markingscheme')),
            ],
        ),
    ]
