# Generated by Django 5.1.2 on 2024-12-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_answer_case_sensitive_answer_grading_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingscheme',
            name='title',
            field=models.CharField(help_text='Title of the marking scheme', max_length=255, null=True),
        ),
    ]
