# Generated by Django 5.1.2 on 2024-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_markingscheme_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='case_sensitive',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='grading_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='order_sensitive',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='range',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='range_sensitive',
        ),
        migrations.RemoveField(
            model_name='markingscheme',
            name='pass_score',
        ),
        migrations.AlterField(
            model_name='markingscheme',
            name='title',
            field=models.CharField(default='title', help_text='Title of the marking scheme', max_length=255),
            preserve_default=False,
        ),
    ]
