# Generated by Django 5.1.3 on 2025-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_answer_case_sensitive_answer_grading_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
