# Generated by Django 5.1.3 on 2025-03-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lecturer_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='University',
            new_name='university',
        ),
    ]
