# Generated by Django 5.1.3 on 2025-03-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_lecturer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='profile_picture',
        ),
    ]
