# Generated by Django 5.1.3 on 2025-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_lecturer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
