# Generated by Django 5.1.3 on 2025-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lecturer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='range',
            field=models.JSONField(blank=True, default=dict, help_text="Range for numerical answers, e.g., {'min': 0, 'max': 100}", null=True),
        ),
    ]
