# Generated by Django 5.1.3 on 2025-04-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_answer_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('student_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('marks_awarded', models.IntegerField(default=0)),
                ('allocated_marks', models.IntegerField()),
                ('grading_type', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='api.submission')),
            ],
            options={
                'unique_together': {('submission', 'question_id')},
            },
        ),
    ]
