# Generated by Django 5.1.3 on 2025-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_answer_partial_matching_answer_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
