version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autogradepro
    ports:
      - "5432:5432"  # Exposing port for debugging
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:11434/api/version || exit 0"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 40s

  # Django Web Application
  web:
    build:
      context: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - submissions_volume:/app/submissions
    networks:
      - app_network
    environment:
      - DJANGO_SETTINGS_MODULE=Server.settings
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autogradepro
      - POSTGRES_HOST=db
      - OLLAMA_HOST=http://ollama:11434
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_change_in_production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    command: >
      bash -c "
        sleep 10 &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn Server.wsgi:application --bind 0.0.0.0:8000
      "

  # Nginx for serving static/media files and as reverse proxy
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - submissions_volume:/app/submissions
    networks:
      - app_network
    depends_on:
      - web

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  submissions_volume:
  ollama_data: