# Django Web Application
  web:
    build:
      context: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - submissions_volume:/app/submissions
    environment:
      - DJANGO_SETTINGS_MODULE=Server.settings
      - DEBUG=False
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autogradepro
      - POSTGRES_HOST=db  # This is critical - must match the service name
      - OLLAMA_HOST=http://ollama:11434
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_change_in_production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    command: >
      bash -c "
        chmod +x wait-for-db.sh &&
        ./wait-for-db.sh db &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn Server.wsgi:application --bind 0.0.0.0:8000
      "